Loaded module: cuda/11.8
Traceback (most recent call last):
  File "/zhome/20/1/209339/02613-Python-and-High-Performance-Computing/week3/Autolab1_3.py", line 51, in <module>
    plt.savefig('figures/performance.png')
  File "/dtu/projects/02613_2025/conda/miniconda3/envs/02613/lib/python3.11/site-packages/matplotlib/pyplot.py", line 1119, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dtu/projects/02613_2025/conda/miniconda3/envs/02613/lib/python3.11/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/dtu/projects/02613_2025/conda/miniconda3/envs/02613/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2187, in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File "/dtu/projects/02613_2025/conda/miniconda3/envs/02613/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "/dtu/projects/02613_2025/conda/miniconda3/envs/02613/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/dtu/projects/02613_2025/conda/miniconda3/envs/02613/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 446, in _print_pil
    mpl.image.imsave(
  File "/dtu/projects/02613_2025/conda/miniconda3/envs/02613/lib/python3.11/site-packages/matplotlib/image.py", line 1656, in imsave
    image.save(fname, **pil_kwargs)
  File "/dtu/projects/02613_2025/conda/miniconda3/envs/02613/lib/python3.11/site-packages/PIL/Image.py", line 2410, in save
    fp = builtins.open(filename, "w+b")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'figures/performance.png'
